# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "debian/buster64"

  config.vm.box_check_update = false

 
  config.vm.define "server" do |machine|
    machine.vm.hostname = 'server'
    machine.vm.provision "shell", path: 'provision.server.sh'
    machine.vm.network "private_network", ip: '192.168.50.10'
  end

  config.vm.define "client" do |machine|
    machine.vm.hostname = 'client'
    machine.vm.provision "shell", path: 'provision.client.sh'
    machine.vm.network "private_network", ip: '192.168.50.20'
  end
end
